# Generated by Django 3.2.7 on 2021-10-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('tabla', models.CharField(choices=[('comunicacion', 'Comunicaciones'), ('tipo_domicilio', 'Tipo de Domicilio'), ('tipo_calle', 'Tipo de Calle'), ('tipo_documento', 'Tipo de Documento')], default='comunicacion', max_length=25)),
                ('texto', models.CharField(max_length=150)),
                ('texto_corto', models.CharField(blank=True, max_length=5, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Diccionario',
                'verbose_name_plural': 'Diccionarios',
                'db_table': 'diccionario',
                'unique_together': {('tabla', 'texto')},
            },
        ),
    ]
