# Generated by Django 3.2.7 on 2021-11-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0004_auto_20211015_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diccionario',
            name='tabla',
            field=models.CharField(choices=[('comunicacion', 'Comunicaciones'), ('tipo_domicilio', 'Tipo de Domicilio'), ('tipo_calle', 'Tipo de Calle')], default='comunicacion', max_length=25),
        ),
    ]
