# Generated by Django 3.1.3 on 2021-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diccionarios', '0005_alter_diccionario_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diccionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
