# Generated by Django 3.2.7 on 2021-10-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211005_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
