# Generated by Django 3.2.7 on 2021-11-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diccionarios', '0004_auto_20211015_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('nombre', models.CharField(max_length=60)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('nombre', models.CharField(max_length=40)),
                ('cod_area_tel', models.CharField(blank=True, max_length=4, null=True, verbose_name='Cód. Area Telef.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('nombre', models.CharField(max_length=60)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domicilios.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('nombre', models.CharField(max_length=150)),
                ('cod_postal', models.CharField(blank=True, max_length=12, null=True, verbose_name='Cód. Postal')),
                ('cod_area_tel', models.CharField(blank=True, max_length=4, null=True, verbose_name='Cód. Area Telef.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidad_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='domicilios.departamento', verbose_name='Dpto.')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidad_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=2, null=True)),
                ('puerta', models.CharField(blank=True, max_length=2, null=True)),
                ('barrio', models.CharField(blank=True, max_length=40, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilio_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='domicilios.departamento', verbose_name='Dpto.')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='domicilios.localidad')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilio_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('provincia', models.ForeignKey(blank=True, default=1, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='domicilios.provincia')),
                ('tipo_calle', models.ForeignKey(blank=True, default=9, limit_choices_to={'active': True, 'tabla': 'tipo_calle'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_calle', to='diccionarios.diccionario')),
                ('tipo_domicilio', models.ForeignKey(blank=True, default=5, limit_choices_to={'active': True, 'tabla': 'tipo_domicilio'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_domicilio', to='diccionarios.diccionario')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilios',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domicilios.provincia'),
        ),
    ]
