# Generated by Django 3.2.7 on 2021-10-06 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('texto', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('tabla', models.CharField(choices=[('comunicacion', 'Comunicaciones'), ('tipo_domicilio', 'Tipo de Domicilio'), ('tipo_calle', 'Tipo de Calle'), ('tipo_documento', 'Tipo de Documento')], default='comunicacion', max_length=25)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diccionario_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diccionario_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Diccionario',
                'verbose_name_plural': 'Diccionarios',
                'db_table': 'diccionario',
            },
        ),
    ]
