# Generated by Django 3.2.7 on 2021-12-11 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0004_alter_persona_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domicilios', '0001_initial'),
        ('telefonos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('domicilio', models.ForeignKey(blank=True, default=1, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='domicilios.domicilio')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('persona', models.ForeignKey(blank=True, default=1, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='ContactosTelefonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacto_telefonos', to='contactos.contacto')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='telefono_contactos', to='telefonos.telefono')),
            ],
            options={
                'verbose_name': 'Contacto y Teléfono',
                'verbose_name_plural': 'Contactos y Teléfonos',
                'db_table': 'contactos_telefonos',
                'unique_together': {('contacto', 'telefono')},
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefonos',
            field=models.ManyToManyField(through='contactos.ContactosTelefonos', to='telefonos.Telefono'),
        ),
    ]
