# Generated by Django 3.2.7 on 2021-10-05 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('nombre', models.CharField(db_index=True, max_length=40)),
                ('apellido', models.CharField(db_index=True, max_length=40)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'D.N.I.'), ('PASS', 'Pasaporte')], default='DNI', max_length=4, verbose_name='Tipo Doc.')),
                ('documento', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Número')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fec. Nac.')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo')),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
    ]
