# Generated by Django 3.2.7 on 2021-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=40)),
                ('apellido', models.CharField(db_index=True, max_length=40)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'D.N.I.'), ('PASS', 'Pasaporte')], default='DNI', max_length=4, verbose_name='Tipo Doc.')),
                ('documento', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Número')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fec. Nac.')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No Binario')], default='M', max_length=1, verbose_name='Sexo')),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
    ]
