# Generated by Django 3.2.7 on 2021-11-09 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diccionarios', '0004_auto_20211015_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modified_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el')),
                ('nombre', models.CharField(db_index=True, max_length=40)),
                ('apellido', models.CharField(db_index=True, max_length=40)),
                ('documento', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Número')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fec. Nac.')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Sexo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('tipo_documento', models.ForeignKey(blank=True, default=12, limit_choices_to={'active': True, 'tabla': 'tipo_documento'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='diccionarios.diccionario', verbose_name='Tipo Doc')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
    ]
